import { createClient } from "@supabase/supabase-js";
import "./style.css";

const charges=["Kaygol 'ana jay' w howa ba9i f dar","Kaychouf message w ma kayjawbch","Kaygol 'derniere game' w kayb9a sa3tin","Kayji ghir mlli kayna lmakla","Kayakol men plat dyal koulchi","Kaykmel flos chhar f simana lwla"];
const punishments=["Ykhless tacos l3chran kamlin 🌮","Y7et akhir conversation f story 24h 📱","Y3red 3la atay w msemen 🫖","L3chran ytfa9o kamlin 3la 7okma wa7da ⚖","Ydwech b 7wayjo w yswrha lina dalil 🚿","Ysift l akhir personne dwa m3aha: 'Rak m3rod l M7kamt L3chran' 😂"];
const url=import.meta.env.VITE_SUPABASE_URL||import.meta.env.NEXT_PUBLIC_SUPABASE_URL,key=import.meta.env.VITE_SUPABASE_ANON_KEY||import.meta.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
const db=url&&key?createClient(url,key):null;
const app=document.querySelector("#app");
let caseFile=null;

const escape=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const shell=content=>app.innerHTML=`<main class="page-shell"><div class="noise"></div><header><button class="brand" id="brand"><span>⚖</span><b>M7KAMT<br>L3CHRAN</b></button></header>${content}</main>`;
const bindBrand=()=>document.querySelector("#brand")?.addEventListener("click",home);
const options=a=>a.map(x=>`<option value="${escape(x)}">${escape(x)}</option>`).join("");
function message(text,type="loading"){document.querySelector(".notice")?.remove();app.insertAdjacentHTML("afterbegin",`<div class="notice ${type}">${escape(text)}</div>`);setTimeout(()=>document.querySelector(".notice")?.remove(),2500)}
function home(){history.replaceState(null,"",location.pathname);shell(`<section class="hero"><p class="eyebrow">Lma7kama ra9m 1 dyal s7ab</p><h1>7akem s7abk<br><em>w khlli l3chran y9rrro</em></h1><p class="lead">Khtar tohmaa, sift lien l3chrank, w chof wach sa7bk modnib wla bari2.</p><button class="primary" id="new">7ell 9adiya jdida →</button><div class="stamp">100%<br>D7k</div></section>`);bindBrand();document.querySelector("#new").onclick=createView}
function createView(){shell(`<section class="card"><div class="step">01 / 7ell l9adiya</div><h2>Chkon howa lmottaham?</h2><label>Smiyat lmottaham</label><input id="name" placeholder="Matalan: Zainab" maxlength="40"><label>Tohmaa</label><select id="charge">${options(charges)}</select><label>L3o9oba ila kan modnib</label><select id="punishment">${options(punishments)}</select><button class="primary full" id="create">Sawb l9adiya ⚖</button><button class="back" id="back">Rj3 llor</button></section>`);bindBrand();document.querySelector("#back").onclick=home;document.querySelector("#create").onclick=createCase}
async function createCase(){if(!db)return message("Khass tconnecta Supabase lwl","error");const name=document.querySelector("#name").value.trim();if(!name)return message("Kteb smiyat lmottaham","error");message("Chwiya... ⚖");const {data,error}=await db.from("cases").insert({name,charge:document.querySelector("#charge").value,punishment:document.querySelector("#punishment").value}).select().single();if(error)return message("Wa9e3 mochkil, 3awed jreb","error");caseFile=data;history.replaceState(null,"",`?case=${data.id}`);voteView()}
function voteView(){shell(`<section class="case-file"><div class="case-number">L9adiya #${escape(caseFile.id.slice(0,6).toUpperCase())}</div><div class="mugshot">${escape(caseFile.name[0].toUpperCase())}</div><p class="accused">Lmottaham</p><h2>${escape(caseFile.name)}</h2><div class="charge"><span>Tohmaa</span><strong>${escape(caseFile.charge)}</strong></div><p class="question">Wach howa modnib wla bari2?</p><div class="vote-grid"><button class="guilty" data-vote="guilty">Modnib 😈</button><button class="innocent" data-vote="innocent">Bari2 😇</button></div><button class="share-link" id="share">Partaji l9adiya m3a l3chran 📲</button></section>`);bindBrand();document.querySelectorAll("[data-vote]").forEach(b=>b.onclick=()=>vote(b.dataset.vote));document.querySelector("#share").onclick=share}
async function vote(choice){message("Kantsjlo vote...");const {data,error}=await db.rpc("vote_case",{p_case_id:caseFile.id,p_vote:choice});if(error||!data?.length)return message("Vote ma tsjjelch, 3awed jreb","error");caseFile=data[0];resultView()}
function resultView(){const g=caseFile.guilty||0,i=caseFile.innocent||0,t=g+i,p=t?Math.round(g/t*100):0,modnib=g>=i;shell(`<section class="card result"><div class="step">L7okm daba</div><div class="verdict ${modnib?"":"innocent-verdict"}">${modnib?"Modnib":"Bari2"}</div><h2>${escape(caseFile.name)} ${modnib?`modnib b nisba dyal ${p}%`:`bari2 b nisba dyal ${100-p}%`}</h2><div class="meter"><span style="width:${p}%"></span></div><p>${g} modnib · ${i} bari2</p>${modnib?`<div class="sentence"><small>L3o9oba</small><strong>${escape(caseFile.punishment)}</strong></div>`:""}<button class="primary full" id="share">Partaji l7okm 📲</button><button class="back" id="new">7ell 9adiya jdida</button></section>`);bindBrand();document.querySelector("#share").onclick=share;document.querySelector("#new").onclick=createView}
async function share(){const shareUrl=`${location.origin}?case=${caseFile.id}`;if(navigator.share)await navigator.share({title:"M7kamt L3chran",text:`Dkhol 7kem 3la ${caseFile.name} 😂⚖`,url:shareUrl});else{await navigator.clipboard.writeText(shareUrl);message("Lien tcopya ✅")}}
async function start(){const id=new URLSearchParams(location.search).get("case");if(!id)return home();if(!db){home();return message("Khass tconnecta Supabase lwl","error")}shell('<div class="center">Chwiya... ⚖</div>');const {data,error}=await db.from("cases").select("*").eq("id",id).single();if(error){home();return message("Had l9adiya mal9inaha-ch","error")}caseFile=data;voteView()}
start();
